# SPDX-FileCopyrightText: Collegiate Edu-Nation
# SPDX-License-Identifier: GPL-3.0-or-later

site_name: easy-ftc docs

repo_name: collegiate-edu-nation/easy-ftc
repo_url: https://github.com/collegiate-edu-nation/easy-ftc

copyright: Copyright Collegiate Edu-Nation

theme:
  features:
    - content.code.copy
  name: "material"
  logo: img/logo/easy-ftc.png
  favicon: img/logo/favicon.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - tables
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Welcome: index.md
  - Getting Started: gettingstarted.md
  - examples.md
  - controls.md
  - naming.md
  - diagrams.md
  - Javadoc: javadoc/index.html
  - license.md
