# SPDX-FileCopyrightText: 2024 Collegiate Edu-Nation
# SPDX-License-Identifier: GPL-3.0-or-later

site_name: easy-ftc docs

repo_name: collegiate-edu-nation/easy-ftc
repo_url: https://github.com/collegiate-edu-nation/easy-ftc

copyright: Copyright 2024 Collegiate Edu-Nation

theme:
  name: "material"
  logo: images/easy-ftc.png
  favicon: images/favicon.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - tables

nav:
  - Welcome: index.md
  - Getting Started: gettingStarted.md
  - examples.md
  - controls.md
  - Javadoc: javadoc/index.html
  - diagrams.md
  - license.md