# SPDX-FileCopyrightText: 2025 Collegiate Edu-Nation
# SPDX-License-Identifier: GPL-3.0-or-later

name: build

on:
  push:
    paths-ignore:
      - "**/README.md"
      - ".github/*.md"
  pull_request:
    paths-ignore:
      - "**/README.md"
      - ".github/*.md"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: setup zulu OpenJDK 21
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
      - name: setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: build myBlocks
        run: ./gradlew myBlocks

      - name: build easy-ftc
        run: ./gradlew build

      - name: build javadoc
        run: ./gradlew apidoc -x uml
