# SPDX-FileCopyrightText: 2025 Collegiate Edu-Nation
# SPDX-License-Identifier: GPL-3.0-or-later

name: build

on:
  push:
    paths-ignore:
      - "**/README.md"
      - ".github/*.md"
  pull_request:
    paths-ignore:
      - "**/README.md"
      - ".github/*.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            trusted-public-keys =
            substituters =
      - name: prepare deps
        run: nix develop
      - name: build myBlocks
        run: nix develop --command bash -c "./gradlew myBlocks"
      - name: build easy-ftc
        run: nix develop --command bash -c "./gradlew build"
      - name: build docs
        run: nix develop --command bash -c "./gradlew docs"
